# Generated by Django 4.2.1 on 2023-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('quote', models.CharField(max_length=100)),
            ],
        ),
    ]
