# Generated by Django 4.2.1 on 2023-06-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membre',
            new_name='Member',
        ),
    ]
