# Generated by Django 4.2.1 on 2023-06-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_member_nom_alter_member_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
